<?php

DEFINE('APP_NAME', 'WEBSTORE');
DEFINE('APP_VERSION', '1.0.0');

//Mysql

DEFINE('MYSQL_SERVER', 'localhost');
DEFINE('MYSQL_DATABASE', 'webstore');
DEFINE('MYSQL_USER', 'root');
DEFINE('MYSQL_PASS', '');
DEFINE('MYSQL_CHARSET', 'UTF-8');
